name: empty workflows
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    #- cron: '*/10 * * * *'
    - cron: '*/5 * * * *'
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: first commit
        run: python main.py

      - name: finishing
        run: |
          git add .
          git config user.name 'yasserbdj96'
          git config user.email 'by.root96@gmail.com'
          git commit -am "Update Files"
          git push 