name: blank workflows
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    #- cron: '*/10 * * * *'
    - cron: '*/5 * * * *'
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: first commit
        run: python main.py

      - name: finishing
        run: |
          git add .
          git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          git commit -am "Update Files"
          git push 