name: empty workflows
on:
  # 
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    #- cron: '*/10 * * * *'
    - cron: '*/10 * * * *'
#defaults:
#  run:
#    working-directory: wrdir
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: step-1
        id: vars
        run: |
          echo "name=production" >> $GITHUB_OUTPUT
          python main.py
        #run: echo ${{ steps.vars.outputs.production }}
      #- name: Print 0
      #  if: ${{ steps.vars.outputs.production == 0 }} 
      #  run: echo "${{ steps.vars.outputs.production }}"
      - name: Update Files
        if: ${{ steps.vars.outputs.production  == 1 }}
        run: |
          git add .
          git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          git commit -am "Update Files"
          git push 
      - name: Do Nothing
        if: ${{ steps.vars.outputs.production  == 0 }}
        run: echo ${{ steps.vars.outputs.production }}
