name: empty workflows
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    #- cron: '*/10 * * * *'
    - cron: '*/5 * * * *'
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: step-1
        id: xyz
        run: python main.py
      
      - name: step-2
        if: steps.xyz.outputs == 0
        run: |
          echo "Number lower than 1"
          echo "${{ steps.xyz.outputs }}"
      
      - name: step-3
        if: steps.xyz.outputs == 1
        run: |
          echo "Number higher than 1"
          echo "${{ steps.xyz.outputs }}"
