name: empty workflows
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    #- cron: '*/10 * * * *'
    - cron: '*/5 * * * *'
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: step-1
        env:
          COMMIT_VAR: python main.py
      
      - name: step-2
        if: ${COMMIT_VAR} == 0
        run: |
          echo "Number lower than 1"
      
      - name: step-3
        if: ${COMMIT_VAR} == 1
        run: |
          echo "Number higher than 1"
