name: empty workflows
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    #- cron: '*/10 * * * *'
    - cron: '*/5 * * * *'
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: step-1
        run: |
          output=$(python main.py)
          output="${output//'%'/'%25'}"
          output="${output//$'\n'/'%0A'}"
          output="${output//$'\r'/'%0D'}" 
          echo "::set-output name=changelog::$output"
        id: step1
      - name: Print changelog
        run: echo "${{ steps.step1.outputs.changelog }}"
