name: empty workflows
on:
  # 
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    #- cron: '*/10 * * * *'
    - cron: '*/10 * * * *'
#defaults:
#  run:
#    working-directory: wrdir
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.production }}
    steps:
      - name: step-1
        run: |
          output=$(python ../main.py)
          output="${output//'%'/'%25'}"
          output="${output//$'\n'/'%0A'}"
          output="${output//$'\r'/'%0D'}"
          echo "${output}"
          echo "name=production::${output}" >> $GITHUB_OUTPUT
        id: step1
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - uses: actions/checkout@v2
      - name: Update Files
        if: ${{ needs.job1.outputs.output1  == 1 }}
        run: |
          git add .
          git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          git commit -am "Update Files"
          git push 
      - name: Do Nothing
        if: ${{ needs.job1.outputs.output1  == 0 }}
        run: echo ${{ needs.job1.outputs.output1 }}
