name: empty workflows
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    #- cron: '*/10 * * * *'
    - cron: '*/5 * * * *'
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: step-1
        id: xyz
        run: python main.py >> $RU
      
      - name: step-2
        if: $RU == "0"
        run: |
          echo "Number lower than 1"
      
      - name: step-3
        if: $RU == "1"
        run: |
          echo "Number higher than 1"
